/**
 *  * Função para buscar repositórios e calcular linguagens
  */
  async function fetchGitHubStats() {
      const username = 'paulorabelo';
          const container = document.getElementById('github-skills-container');

              try {
                      // 1. Busca todos os repositórios públicos do usuário
                              const response = await fetch(`https://api.github.com/users/${username}/repos?per_page=100`);
                                      const repos = await response.json();

                                              const languageMap = {};
                                                      let totalSize = 0;

                                                              // 2. Soma o tamanho (bytes) de cada linguagem encontrada
                                                                      repos.forEach(repo => {
                                                                                  if (repo.language) {
                                                                                                  languageMap[repo.language] = (languageMap[repo.language] || 0) + 1; 
                                                                                                                  // Nota: Para maior precisão, poderíamos buscar detalhes de cada repo, 
                                                                                                                                  // mas contar a frequência por repo é mais rápido para a API.
                                                                                                                                                  totalSize++;
                                                                                                                                                              }
                                                                                                                                                                      });

                                                                                                                                                                              // 3. Limpa o container de "Carregando"
                                                                                                                                                                                      container.innerHTML = '';

                                                                                                                                                                                              // 4. Cria o HTML para cada linguagem encontrada
                                                                                                                                                                                                      Object.keys(languageMap).forEach(lang => {
                                                                                                                                                                                                                  const percentage = Math.round((languageMap[lang] / totalSize) * 100);
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                          // Criando a estrutura compatível com seu CSS
                                                                                                                                                                                                                                                      const skillHTML = `
                                                                                                                                                                                                                                                                      <div class="skill-item">
                                                                                                                                                                                                                                                                                          <span>${lang}</span>
                                                                                                                                                                                                                                                                                                              <div class="progress-bar-container">
                                                                                                                                                                                                                                                                                                                                      <div class="progress-bar" style="width: ${percentage}%">
                                                                                                                                                                                                                                                                                                                                                                  ${percentage}%
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      container.innerHTML += skillHTML;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('Erro ao buscar dados do GitHub:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  container.innerHTML = '<p>Não foi possível carregar as habilidades no momento.</p>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Executa a função ao carregar a página
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      window.onload = fetchGitHubStats;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 */